#!/usr/bin/env python3
"""
A script to run a competition match.
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

sys.path.insert(1, str(REPO_ROOT / 'modules'))

import match_utils  # isort:skip

if __name__ == '__main__':
    match = match_utils.Match()
    match.main(match.parse_args())
